name: Run Countdown Bot

on:
  schedule:
    - cron: '30 18 * * *'  # Runs every day at 18:30 UTC (12:00 AM IST)
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Update to the latest version

      - name: Set up Python
        uses: actions/setup-python@v3  # Update to the latest version
        with:
          python-version: '3.10'  # Use a stable version

      - name: Install dependencies
        run: pip install tweepy

      - name: Run countdown bot
        run: python main.py
        env:
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET_KEY: ${{ secrets.TWITTER_API_SECRET_KEY }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
